project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Central York Science Olympiad"
  description: "Central York High School Science Olympiad"
  site-url: "https://coen-beamesderfer.github.io/cyhs-scioly/"
  favicon: images/CYHSso.png
  page-navigation: true

  navbar:
    background: dark
    logo: images/CYHSso.png
    title: "CYHS Science Olympiad"

    left:
      - href: index.qmd
        text: Home

      - href: about.qmd
        text: About

      - href: stats.qmd
        text: Statistics

      - href: schedule.qmd
        text: Schedule

      - href: sponsor.qmd
        text: Support Us

      - href: contact.qmd
        text: Join Us

    right:
      - icon: instagram
        href: https://www.instagram.com/cyhsscioly/
        aria-label: Instagram

  page-footer:
    left: "© 2026 Central York Science Olympiad"
    center:
     - |
       <div class="footer-sponsors">
          <span>Proudly supported by</span>
          <a href="https://www.csdavidson.com/" aria-label="C.S. Davidson, Inc.">
            <img src="images/cs-davidson.png" alt="C.S. Davidson, Inc.">
         </a>
         <a href="https://www.janestreet.com/" aria-label="Jane Street">
           <img src="images/jane-street.png" alt="Jane Street">
         </a>
       </div>
    right: "Built with [Quarto](https://quarto.org)"
    background: dark

format:
  html:
    theme: [flatly, styles.scss]
    toc: false
    link-external-newwindow: true